pipeline {
    agent any

    environment {
        VENV_DIR = "venv"  // No need for full path if it's in the project root directory
        MLFLOW_TRACKING_URI = "http://localhost:5000"
        FASTAPI_HOST = "0.0.0.0"
        FASTAPI_PORT = "8000"
    }

    stages {
        stage('Setup Environment') {
            steps {
                echo 'Setting up Virtual Environment...'
                sh '''
                    python3 -m venv $VENV_DIR
                    . $VENV_DIR/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt --quiet
                '''
            }
        }

        stage('Start MLflow Server') {
            steps {
                echo 'Starting MLflow Tracking Server...'
                sh '''
                    . $VENV_DIR/bin/activate
                    mlflow ui --host 0.0.0.0 --port 5000 &
                '''
                sleep 5
            }
        }

        

        stage('Train Models') {
            steps {
                echo 'Training Models...'
                sh '''
                    . $VENV_DIR/bin/activate
                    python main.py --train --model decision_tree
                    
                '''
            }
        }

        stage('Deploy FastAPI') {
            steps {
                echo 'Deploying FastAPI Server...'
                sh '''
                    . $VENV_DIR/bin/activate
                    nohup uvicorn fastapi_app.api:app --host $FASTAPI_HOST --port $FASTAPI_PORT &
                '''
                sleep 5
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully! ✅'
        }
        failure {
            echo 'Pipeline failed. Check logs. ❌'
        }
    }
}
